# Minimal preset - Electra

# Max operations per block
# ---------------------------------------------------------------
# 2**4 (= 16)
MAX_EXECUTION_LAYER_EXITS: 16

# Execution
# ---------------------------------------------------------------
# [customized]
MAX_DEPOSIT_RECEIPTS_PER_PAYLOAD: 4

# Updated max operations per block
# ---------------------------------------------------------------
# 2**0 (= 1)
MAX_ATTESTER_SLASHINGS_ELECTRA: 1
# 2**3 (= 8)
MAX_ATTESTATIONS_ELECTRA: 8